import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#caf0f8',
        alignItems: 'center',
        justifyContent: 'center',
        padding: 20,
    },
    logo: {
        width: 100,
        height: 100,
        marginBottom: 20,
        borderRadius: 15,
        backgroundColor: '#ffffffcc',
        padding: 10,
    },
    card: {
        backgroundColor: '#ffffff',
        borderRadius: 25,
        padding: 30,
        width: '100%',
        maxWidth: 400,
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 7 },
        shadowOpacity: 0.15,
        shadowRadius: 10,
        elevation: 10,
    },
    icon: {
        marginBottom: 12,
    },
    title: {
        fontSize: 28,
        fontWeight: '700',
        color: '#0077b6',
        marginBottom: 25,
    },
    input: {
        width: '100%',
        backgroundColor: '#e0f7fa',
        padding: 14,
        borderRadius: 12,
        marginBottom: 20,
        fontSize: 16,
        color: '#0077b6',
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#e0f7fa',
        borderRadius: 12,
        marginBottom: 20,
        width: '100%',
    },
    passwordInput: {
        flex: 1,
        paddingVertical: 14,
        paddingHorizontal: 14,
        fontSize: 16,
        color: '#0077b6',
    },
    eyeIcon: {
        paddingHorizontal: 12,
    },
    button: {
        backgroundColor: '#00b4d8',
        paddingVertical: 15,
        paddingHorizontal: 30,
        borderRadius: 12,
        width: '100%',
        alignItems: 'center',
        marginTop: 5,
        shadowColor: '#0077b6',
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.35,
        shadowRadius: 6,
        elevation: 7,
    },
    buttonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 17,
    },
    link: {
        marginTop: 18,
        color: '#0077b6',
        fontSize: 15,
        textDecorationLine: 'underline',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: '#00000099',
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    alertBox: {
        backgroundColor: '#fff',
        padding: 30,
        borderRadius: 20,
        width: '85%',
        maxWidth: 350,
        alignItems: 'center',
        shadowColor: '#d00000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    alertText: {
        marginTop: 18,
        fontSize: 17,
        color: '#333',
        textAlign: 'center',
    },
    alertButton: {
        marginTop: 25,
        backgroundColor: '#0077b6',
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 10,
    },
    alertButtonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 16,
    },
    successBox: {
        backgroundColor: '#fff',
        padding: 30,
        borderRadius: 20,
        width: '85%',
        maxWidth: 350,
        alignItems: 'center',
        shadowColor: '#28a745',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 10,
    },
    successText: {
        marginTop: 20,
        fontSize: 20,
        fontWeight: '700',
        color: '#28a745'
    }
});
